spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/chevrolet
    username: postgres
    password: uiisisdu9
    driverClassName: org.postgresql.Driver