spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/chevrolet
    username: postgres
    password: lel
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 292687563dfb8
    password: 51d0a9cb50e31
    protocol: smtp
    test-connection: true